// <auto-generated />
namespace PeriodicalsFinal.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DatabaseGeneratedOption_Set_To_none_SubscribeModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatabaseGeneratedOption_Set_To_none_SubscribeModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201906291659586_DatabaseGeneratedOption_Set_To_none_SubscribeModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
