// <auto-generated />
namespace PeriodicalsFinal.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Relation_UserSubscription_Fix1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relation_UserSubscription_Fix1));
        
        string IMigrationMetadata.Id
        {
            get { return "201906191117026_Relation_User-Subscription_Fix1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
